FROM node:14.16-alpine

RUN mkdir app
WORKDIR /app

RUN apk update && apk add -U tzdata && cp /usr/share/zoneinfo/Asia/Tashkent /etc/localtime && apk del tzdata

COPY package*.json ./
RUN npm install

COPY . ./
RUN cp .env.development .env
RUN npm run-script build

ENV NODE_ENV=development
ENV HOST=0.0.0.0
EXPOSE 3000
ENTRYPOINT ["npm", "start"]